#!/bin/bash

for i in `ls -d database/*` ; do
	if [ ! -f "$i" ] ; then
		continue
	elif [ "${i%%.*}" != "$i" ] ; then
		continue
	fi
	base="${i##*/}"

	[ "database/${base:0:1}/$base" -ot "$i" ] || continue

	[ -d "database/${base:0:1}" ] || mkdir -p "database/${base:0:1}" > /dev/null
	echo "== Compiling $base =="
	../src.util/t3keyc -o "database/${base:0:1}/$base" "$i"
done