#!/bin/bash
# Copyright (C) 2011 G.P. Halkes
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

for i in `ls -d database/*` ; do
	if [ ! -f "$i" ] ; then
		continue
	elif [ "${i%%.*}" != "$i" ] ; then
		continue
	fi
	base="${i##*/}"

	[ "database/${base:0:1}/$base" -ot "$i" ] || continue

	[ -d "database/${base:0:1}" ] || mkdir -p "database/${base:0:1}" > /dev/null
	echo "== Compiling $base =="
	../src.util/t3keyc/t3keyc -d "database" "$i"
done
